Repository pagopa/pagopa-afm-fee-reporting-service, pull requests merged in 2025-07, with the labels that each got.

#19 feat: add satispay and sella policy url
  .github/workflows/update_fee_reporting_file.yml
Labels: enhancement, size/small, patch

#20 fix: typo in psp-policy-url
  .github/workflows/update_fee_reporting_file.yml
Labels: bug, size/small, patch

#18 [PIDM-497] fix: update helm chart version and wl identity ref
  .github/workflows/deploy_with_github_runner.yml
  .identity/00_data.tf
  .identity/01_github_environment.tf
  .identity/99_main.tf
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small
